apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jfrog-repo
on:
  push:
    branches:
      - 'jfrog-artifactory-upload-file'

jobs:
  jfrog-repo-job:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1

      # Upload file "/test/jfrog_repo_test1.zip" from local to artifactory repository "example-repo-local"
      - name: jfrog-actions-workflow-upload-file
        uses: cloudbees-io/jfrog-artifactory-upload-file-private@CBP-7099
        with:
          url: ${{ vars.JFROG_URL }}
          username: ${{ vars.JFROG_ACTIONS_USERNAME }}
          password: ${{ secrets.JFROG_ACTIONS_PASSWORD }}
          file-path: ${{ cloudbees.workspace }}/test/jfrog_repo_test1.zip
          artifactory-path: example-repo-local/jfrogtest/test1.zip
