apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jfrog-repo
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  jfrog-repo-job:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: jfrog-actions-workflow-upload-file
        uses: cloudbees-io/jfrog-artifactory-upload-file@v1
        with:
          url: ${{ vars.JFROG_URL }}
          token: ${{ secrets.JFROG_ACTIONS_TOKEN }}
          # username: ${{ vars.JFROG_ACTIONS_USERNAME }}
          # password: ${{ secrets.JFROG_ACTIONS_PASSWORD }}
          file-path: ${{ cloudbees.workspace }}/test/jfrog_repo_test.zip
          artifactory-path: example-repo-local/jfrogtest/test.zip
